name: app_environment
channels:
  - snowflake
dependencies:
  - pandas=2.2.3
  - python=3.10.*
  - snowflake-ml-python=1.23.0
  - snowflake-snowpark-python=
  - streamlit=
  - trulens-connectors-snowflake=2.4.2
  - trulens-core=2.4.2
  - trulens-providers-cortex=2.4.2
